#Application
spring:
  application:
    name: SECURITY-SERVICE
#  datasource:
#    url: jdbc:mysql://localhost:3306/movie_theater
#    username: root
#    password:
#    driverClassName: com.mysql.cj.jdbc.Driver
#  jpa:
#    hibernate.ddl-auto: create-drop
#    generate-ddl: true
#    show-sql: true

server:
  port: 8081

#Variable